sudo: false
language: ruby
notifications:
  email:
    - travis-ci.com+qkunst@murb.nl
rvm:
  - 2.7.3
before_install:
  - gem install bundler
  - nvm install
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - docker-compose up -d
script:
  - bundle exec rails db:test:prepare
  - sleep 20 #making sure all services (notably elastic search) is up and running
  - curl -u elastic:PleaseChangeMe -X GET "localhost:59200"
  - RAILS_ENV=test bundle exec rails qkunst:new_index_and_sync
  - sleep 2
  - bundle exec bundle audit update
  - bundle exec bundle audit check
  - "curl -u elastic:PleaseChangeMe -X PUT \"localhost:59200/_settings\" -H 'Content-Type: application/json' -d '{ \"index\" : { \"max_result_window\" : 5000000 } }'"
  - bundle exec rspec
services:
  - docker
  - redis
  - postgresql
cache:
  rvm: true
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  postgresql: "9.4"
# safelist
branches:
  only:
  - main
  - develop