sudo: false
language: ruby
cache: bundler
notifications:
  email:
    - travis-ci.com+qkunst@murb.nl
rvm:
  - 2.4.1
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
before_install:
  - gem install bundler
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
services:
  - elasticsearch
  - postgresql
addons:
  postgresql: "9.4"
# safelist
branches:
  only:
  - master
  - develop