sudo: false
language: ruby
notifications:
  email:
    - travis-ci.com+qkunst@murb.nl
rvm:
  - 2.6.2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - docker-compose up -d
before_install:
  - gem install bundler
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
script:
  - bundle exec rails db:test:prepare
  - bundle exec rails qkunst:new_index
  - sleep 5
  - bundle exec rspec
services:
  - docker
  - redis
  - postgresql
cache:
  rvm: true
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  postgresql: "9.4"
# safelist
branches:
  only:
  - master
  - develop