# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec3fca8ccc9fce4953d641fb669be639009d9e33ca10d2dc022d15d06f9d7d33bd7bfc1205557ddd84b8996772883d5424f78b9f143eea2d5bf5bd806113be6

test:
  secret_key_base: a05f809bb2890d1f1d3ae1181598b8bc6f9c3ba1c2fa4ef80b8573ba59f33c588cf966432fb8dacb4373121e28dd2d6f8268744101589db1e23aad49d9db5844

# Merk op dat standaard wordt gesuggereerd om de `SECRET_KEY_BASE` als een
# environment variabele te communiceren, maar aangezien de database
# configuratie ook al met een 'shared'-file actie werkt heb ik deze wijze
# ook gebruikt voor secrets.yml

testing:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repositor y,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
